# SONM active deal analyzer

## This notebook is to analyze active deals on the SONM platform in real-time.

### Import necessary libraries

In [1]:
import pandas as pd
import numpy as np

### SONM's DWH spits out API information of active deals.  Using Jupyter's magic to run BASH command to save the API data to livedeal.txt

In [2]:
!curl -s https://dwh.livenet.sonm.com:15022/DWHServer/GetDeals/ -d '{"status":1}' > livedeal.txt

### Open the saved text in Jupyter

In [3]:
f = open('livedeal.txt','r')

### Convert opened file to Pandas dataframe.

In [4]:
k = f.readlines()

In [5]:
r = k[0].split(',')

In [6]:
headposition = []
i = 0
for item in r:
    if 'deal' in item:

        headposition.append(i)
    i = i+1

In [7]:
testlist = []
for i in range(len(headposition)):
    if headposition[i]>0:
        #print(headposition[i-1], headposition[i])
        #print(r[headposition[i-1] : headposition[i]])
        testlist.append(r[headposition[i-1] : headposition[i]])

In [8]:
df = pd.DataFrame(testlist)

In [9]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,"{""deals"":[{""deal"":{""id"":""4582""","""benchmarks"":{""values"":[501",718,1,524288000,10737418240,5242880,5242880,0,0,...,"""status"":1","""blockedBalance"":""182805093337395992""","""totalPayout"":""7139972413411286969""","""lastBillTS"":""2018-08-21T23:40:34Z""}","""netflags"":7","""askIdentityLevel"":3","""bidIdentityLevel"":1","""supplierCertificates"":""W3sib3duZXJJRCI6IjB4Qj...","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4Qj...",None
1,"{""deal"":{""id"":""3471""","""benchmarks"":{""values"":[1004",513,6,256000000,67108864,1000000,1000000,0,0,...,"""status"":1","""blockedBalance"":""176334931959376""","""totalPayout"":""51456177132850741""","""lastBillTS"":""2018-08-21T23:40:13Z""}","""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4MT...",None
2,"{""deal"":{""id"":""4135""","""benchmarks"":{""values"":[503",866,1,256000000,67108864,1000000,1000000,0,0,...,"""status"":1","""blockedBalance"":""0""","""totalPayout"":""0""","""lastBillTS"":""2018-08-21T23:39:04Z""}","""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W10=""}",None
3,"{""deal"":{""id"":""1450""","""benchmarks"":{""values"":[102",513,6,4194304,67108864,1200,1001,0,0,...,"""status"":1","""blockedBalance"":""0""","""totalPayout"":""0""","""lastBillTS"":""2018-08-21T23:38:52Z""}","""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W10=""}",None
4,"{""deal"":{""id"":""4692""","""benchmarks"":{""values"":[114",1525,4,512000000,67108864,1000000,1000000,2,8513388544,...,"""status"":1","""blockedBalance"":""991067211436687152""","""totalPayout"":""10271171002160646349""","""lastBillTS"":""2018-08-21T23:38:40Z""}","""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W3sib3duZXJJRCI6IjB4NT...","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4ND...",None

## Data Cleaning

### The 14 column contains consumer ID.  First clean this colum.

In [10]:
df[14]

0     "consumerID":"0xB4214d064518eed303D966F9ca0Fc6...
1     "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
2     "consumerID":"0xEe7Ff0a44C62209aa7dAa450F67341...
3     "consumerID":"0x49f6C95B97C209F814c5b3B13428E9...
4     "consumerID":"0x417c92FbD944b125A578848DE44a4F...
5     "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
6     "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
7     "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
8     "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
9     "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
10    "consumerID":"0xF044524c6A30bC7559DEa1CB21fA11...
11    "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
12    "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
13    "consumerID":"0xAAA932d77935EE3d8E0Ba1d464CFDA...
14    "consumerID":"0x417c92FbD944b125A578848DE44a4F...
15    "consumerID":"0x417c92FbD944b125A578848DE44a4F...
16    "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
17    "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
18    "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
19    "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
20    "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
21    "consumerID":"0x417c92FbD944b125A578848DE44a4F...
22    "consumerID":"0x49f6C95B97C209F814c5b3B13428E9...
23    "consumerID":"0x18CB84498d67635F14BA20A7A5DD9F...
24    "consumerID":"0x417c92FbD944b125A578848DE44a4F...
25    "consumerID":"0xc620838fcaec0e5559aa111f77FC60...
26    "consumerID":"0x6f74D76F4c4b80A61598bdED7Fca2f...
27    "consumerID":"0xe7517190DB97Ea55E985abdA33745A...
28    "consumerID":"0x49f6C95B97C209F814c5b3B13428E9...
Name: 14, dtype: object

### Make a little funtion to trim unnecessary charactors

In [11]:
def Supplier_ID_conversion(content):
    return content[14:-1]

###  And applyt to pandas data frame.  New column called consumer_ID is generated.

In [12]:
df['consumer_ID'] = df[14].apply(Supplier_ID_conversion)

In [13]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,consumer_ID
0,"{""deals"":[{""deal"":{""id"":""4582""","""benchmarks"":{""values"":[501",718,1,524288000,10737418240,5242880,5242880,0,0,...,"""blockedBalance"":""182805093337395992""","""totalPayout"":""7139972413411286969""","""lastBillTS"":""2018-08-21T23:40:34Z""}","""netflags"":7","""askIdentityLevel"":3","""bidIdentityLevel"":1","""supplierCertificates"":""W3sib3duZXJJRCI6IjB4Qj...","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4Qj...",None,0xB4214d064518eed303D966F9ca0Fc62Ac8dF20EE
1,"{""deal"":{""id"":""3471""","""benchmarks"":{""values"":[1004",513,6,256000000,67108864,1000000,1000000,0,0,...,"""blockedBalance"":""176334931959376""","""totalPayout"":""51456177132850741""","""lastBillTS"":""2018-08-21T23:40:13Z""}","""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4MT...",None,0x18CB84498d67635F14BA20A7A5DD9F8254bA5ecb
2,"{""deal"":{""id"":""4135""","""benchmarks"":{""values"":[503",866,1,256000000,67108864,1000000,1000000,0,0,...,"""blockedBalance"":""0""","""totalPayout"":""0""","""lastBillTS"":""2018-08-21T23:39:04Z""}","""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W10=""}",None,0xEe7Ff0a44C62209aa7dAa450F673415bC90bFC11
3,"{""deal"":{""id"":""1450""","""benchmarks"":{""values"":[102",513,6,4194304,67108864,1200,1001,0,0,...,"""blockedBalance"":""0""","""totalPayout"":""0""","""lastBillTS"":""2018-08-21T23:38:52Z""}","""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W10=""}",None,0x49f6C95B97C209F814c5b3B13428E91686a1FEd9
4,"{""deal"":{""id"":""4692""","""benchmarks"":{""values"":[114",1525,4,512000000,67108864,1000000,1000000,2,8513388544,...,"""blockedBalance"":""991067211436687152""","""totalPayout"":""10271171002160646349""","""lastBillTS"":""2018-08-21T23:38:40Z""}","""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W3sib3duZXJJRCI6IjB4NT...","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4ND...",None,0x417c92FbD944b125A578848DE44a4FD9132E0911

## supplier

###  Same trick for the supplier ID.  The 13 column contains supplier ID information.  Clean with the same function.

In [14]:
df[13]

0     "supplierID":"0x844cae5EADD22CaE667F37388D788f...
1     "supplierID":"0x8546601F9b4AcF1dc99C72cc48ED24...
2     "supplierID":"0x825FfDAB7d275dBAC844eFc36d5E8c...
3     "supplierID":"0x8546601F9b4AcF1dc99C72cc48ED24...
4     "supplierID":"0xC1bf17F560FA5BF79aF72B4314d147...
5     "supplierID":"0x7Cc1C96E6c20D6265531196d9ca2b3...
6     "supplierID":"0x7E74e1034bD9270482Fd286F03Cf7F...
7     "supplierID":"0x37d7Ae51C3421474709331898B278D...
8     "supplierID":"0x26200241593722FA17DE5722Ed66d8...
9     "supplierID":"0x91E0fA215FEc1F7D905f59F7FE03F9...
10    "supplierID":"0xc364C71bAFAA85671C4d45E5Cf61bf...
11    "supplierID":"0x91E0fA215FEc1F7D905f59F7FE03F9...
12    "supplierID":"0x7Cc1C96E6c20D6265531196d9ca2b3...
13    "supplierID":"0x1E575FB7dD8b28CEcAD9065A7aFD1a...
14    "supplierID":"0xd8B606a3D19C53E6Eea84ca5738D7D...
15    "supplierID":"0x2f1B94E3813d66967a478031889F23...
16    "supplierID":"0x7Cc1C96E6c20D6265531196d9ca2b3...
17    "supplierID":"0x8546601F9b4AcF1dc99C72cc48ED24...
18    "supplierID":"0x730F19B7FA079EBfDc7360066ec593...
19    "supplierID":"0x47012859fC5cB44d6106D54ff77580...
20    "supplierID":"0xaE7DB91DeC00E3Be062C7dC3328859...
21    "supplierID":"0x672Ee945a55327328472B1a0243729...
22    "supplierID":"0xAe4fD4581D82C615105c798c73d1C3...
23    "supplierID":"0x70eC78FAF2CcD3fA3fe9567Fa5B835...
24    "supplierID":"0x734C2a165e57496169aAAEA6E22aE7...
25    "supplierID":"0x323FB5f356088ae979F12f27f94013...
26    "supplierID":"0xd87e862c34C5FEE08db543D851089a...
27    "supplierID":"0xe8D423ca11ED809565BFA247d974d6...
28    "supplierID":"0xC3C8b2915f62956066eD5C8719814e...
Name: 13, dtype: object

In [15]:
df['supplier_ID'] = df[13].apply(Supplier_ID_conversion)

### Price

### Price value needs to be adjusted to snm/h later.  I don't know the unit of this value yet.

In [16]:
def Price_conversion(content):
    if 'price' in content:
        return int(content[9:-1])
    if 'duration' in content:
        return int(content[11:-1])

In [17]:
df['price'] = df[18].apply(Price_conversion)

###  ETH has rate

### The 10 column contains Ethash value.  Clean and convert to Mh/s.

In [18]:
df[10]

0             0
1             0
2             0
3             0
4      59117000
5             0
6      64894000
7      85636000
8     219539000
9             0
10            0
11            0
12            0
13     21959000
14    159643000
15     30105000
16            0
17            0
18     12220000
19     22179000
20            0
21    186411000
22            0
23    129860000
24     19778000
25            0
26            0
27            0
28            0
Name: 10, dtype: object

In [19]:
float(df[10][0])/1000000

0.0

In [20]:
def Ethash_conversion(content):
    return float(content)/1000000

In [21]:
Ethash_conversion(df[10][0])

0.0

In [22]:
df['Ethash'] = df[10].apply(Ethash_conversion)

In [23]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,consumer_ID,supplier_ID,price,Ethash
0,"{""deals"":[{""deal"":{""id"":""4582""","""benchmarks"":{""values"":[501",718,1,524288000,10737418240,5242880,5242880,0,0,...,"""netflags"":7","""askIdentityLevel"":3","""bidIdentityLevel"":1","""supplierCertificates"":""W3sib3duZXJJRCI6IjB4Qj...","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4Qj...",None,0xB4214d064518eed303D966F9ca0Fc62Ac8dF20EE,0x844cae5EADD22CaE667F37388D788f79BDd97e62,2777777777777,0.000
1,"{""deal"":{""id"":""3471""","""benchmarks"":{""values"":[1004",513,6,256000000,67108864,1000000,1000000,0,0,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4MT...",None,0x18CB84498d67635F14BA20A7A5DD9F8254bA5ecb,0x8546601F9b4AcF1dc99C72cc48ED243d119cca95,2777777777,0.000
2,"{""deal"":{""id"":""4135""","""benchmarks"":{""values"":[503",866,1,256000000,67108864,1000000,1000000,0,0,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W10=""}",None,0xEe7Ff0a44C62209aa7dAa450F673415bC90bFC11,0x825FfDAB7d275dBAC844eFc36d5E8ce632d8E7A0,0,0.000
3,"{""deal"":{""id"":""1450""","""benchmarks"":{""values"":[102",513,6,4194304,67108864,1200,1001,0,0,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W10=""}",None,0x49f6C95B97C209F814c5b3B13428E91686a1FEd9,0x8546601F9b4AcF1dc99C72cc48ED243d119cca95,0,0.000
4,"{""deal"":{""id"":""4692""","""benchmarks"":{""values"":[114",1525,4,512000000,67108864,1000000,1000000,2,8513388544,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W3sib3duZXJJRCI6IjB4NT...","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4ND...",None,0x417c92FbD944b125A578848DE44a4FD9132E0911,0xC1bf17F560FA5BF79aF72B4314d14706b90ad2cE,14615185000000,59.117

# Run statistics for suppliers

In [24]:
df.groupby('supplier_ID').describe()['Ethash']

,count,mean,std,min,25%,50%,75%,max
supplier_ID,,,,,,,,
0x1E575FB7dD8b28CEcAD9065A7aFD1aC6c2fBA797,1.0,21.959,NaN,21.959,21.959,21.959,21.959,21.959
0x26200241593722FA17DE5722Ed66d8830dc58C6D,1.0,219.539,NaN,219.539,219.539,219.539,219.539,219.539
0x2f1B94E3813d66967a478031889F230D805130Ec,1.0,30.105,NaN,30.105,30.105,30.105,30.105,30.105
0x323FB5f356088ae979F12f27f94013e449BC62df,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
0x37d7Ae51C3421474709331898B278D8bAB66eCac,1.0,85.636,NaN,85.636,85.636,85.636,85.636,85.636
0x47012859fC5cB44d6106D54ff77580c85C380ecc,1.0,22.179,NaN,22.179,22.179,22.179,22.179,22.179
0x672Ee945a55327328472B1a02437293945157f4C,1.0,186.411,NaN,186.411,186.411,186.411,186.411,186.411
0x70eC78FAF2CcD3fA3fe9567Fa5B8354Faa4e9457,1.0,129.860,NaN,129.860,129.860,129.860,129.860,129.860
0x730F19B7FA079EBfDc7360066ec593e4Bdd46Bf2,1.0,12.220,NaN,12.220,12.220,12.220,12.220,12.220
0x734C2a165e57496169aAAEA6E22aE763fF8d7654,1.0,19.778,NaN,19.778,19.778,19.778,19.778,19.778
0x7Cc1C96E6c20D6265531196d9ca2b3199fF8Ef9E,3.0,0.000,0.0,0.000,0.000,0.000,0.000,0.000
0x7E74e1034bD9270482Fd286F03Cf7Fa26Bb99805,1.0,64.894,NaN,64.894,64.894,64.894,64.894,64.894
0x825FfDAB7d275dBAC844eFc36d5E8ce632d8E7A0,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
0x844cae5EADD22CaE667F37388D788f79BDd97e62,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
0x8546601F9b4AcF1dc99C72cc48ED243d119cca95,3.0,0.000,0.0,0.000,0.000,0.000,0.000,0.000
0x91E0fA215FEc1F7D905f59F7FE03F9EF5090A8A8,2.0,0.000,0.0,0.000,0.000,0.000,0.000,0.000
0xAe4fD4581D82C615105c798c73d1C33403d86ACB,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
0xC1bf17F560FA5BF79aF72B4314d14706b90ad2cE,1.0,59.117,NaN,59.117,59.117,59.117,59.117,59.117
0xC3C8b2915f62956066eD5C8719814e276A7B8C00,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
0xaE7DB91DeC00E3Be062C7dC33288597DF023e0d6,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
0xc364C71bAFAA85671C4d45E5Cf61bf19E0225AEb,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
0xd87e862c34C5FEE08db543D851089a59589438d7,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000
0xd8B606a3D19C53E6Eea84ca5738D7D7d2c0eeb5f,1.0,159.643,NaN,159.643,159.643,159.643,159.643,159.643
0xe8D423ca11ED809565BFA247d974d6EB42eB2DBb,1.0,0.000,NaN,0.000,0.000,0.000,0.000,0.000

In [25]:
df10 = df.groupby('supplier_ID').describe()['Ethash']

In [26]:
df10.to_csv('eth.csv')

In [27]:
df11 = pd.read_csv('eth.csv')

In [28]:
df11['total_Ethash']= df11['count']*df11['mean']

In [29]:
df11[['supplier_ID','total_Ethash','count']]

                                   supplier_ID  total_Ethash  count
0   0x1E575FB7dD8b28CEcAD9065A7aFD1aC6c2fBA797        21.959    1.0
1   0x26200241593722FA17DE5722Ed66d8830dc58C6D       219.539    1.0
2   0x2f1B94E3813d66967a478031889F230D805130Ec        30.105    1.0
3   0x323FB5f356088ae979F12f27f94013e449BC62df         0.000    1.0
4   0x37d7Ae51C3421474709331898B278D8bAB66eCac        85.636    1.0
5   0x47012859fC5cB44d6106D54ff77580c85C380ecc        22.179    1.0
6   0x672Ee945a55327328472B1a02437293945157f4C       186.411    1.0
7   0x70eC78FAF2CcD3fA3fe9567Fa5B8354Faa4e9457       129.860    1.0
8   0x730F19B7FA079EBfDc7360066ec593e4Bdd46Bf2        12.220    1.0
9   0x734C2a165e57496169aAAEA6E22aE763fF8d7654        19.778    1.0
10  0x7Cc1C96E6c20D6265531196d9ca2b3199fF8Ef9E         0.000    3.0
11  0x7E74e1034bD9270482Fd286F03Cf7Fa26Bb99805        64.894    1.0
12  0x825FfDAB7d275dBAC844eFc36d5E8ce632d8E7A0         0.000    1.0
13  0x844cae5EADD22CaE667F37388D788f79BDd97e62         0.000    1.0
14  0x8546601F9b4AcF1dc99C72cc48ED243d119cca95         0.000    3.0
15  0x91E0fA215FEc1F7D905f59F7FE03F9EF5090A8A8         0.000    2.0
16  0xAe4fD4581D82C615105c798c73d1C33403d86ACB         0.000    1.0
17  0xC1bf17F560FA5BF79aF72B4314d14706b90ad2cE        59.117    1.0
18  0xC3C8b2915f62956066eD5C8719814e276A7B8C00         0.000    1.0
19  0xaE7DB91DeC00E3Be062C7dC33288597DF023e0d6         0.000    1.0
20  0xc364C71bAFAA85671C4d45E5Cf61bf19E0225AEb         0.000    1.0
21  0xd87e862c34C5FEE08db543D851089a59589438d7         0.000    1.0
22  0xd8B606a3D19C53E6Eea84ca5738D7D7d2c0eeb5f       159.643    1.0
23  0xe8D423ca11ED809565BFA247d974d6EB42eB2DBb         0.000    1.0

In [30]:
df11[['supplier_ID','total_Ethash','count']].sort_values('total_Ethash', ascending = False)

                                   supplier_ID  total_Ethash  count
1   0x26200241593722FA17DE5722Ed66d8830dc58C6D       219.539    1.0
6   0x672Ee945a55327328472B1a02437293945157f4C       186.411    1.0
22  0xd8B606a3D19C53E6Eea84ca5738D7D7d2c0eeb5f       159.643    1.0
7   0x70eC78FAF2CcD3fA3fe9567Fa5B8354Faa4e9457       129.860    1.0
4   0x37d7Ae51C3421474709331898B278D8bAB66eCac        85.636    1.0
11  0x7E74e1034bD9270482Fd286F03Cf7Fa26Bb99805        64.894    1.0
17  0xC1bf17F560FA5BF79aF72B4314d14706b90ad2cE        59.117    1.0
2   0x2f1B94E3813d66967a478031889F230D805130Ec        30.105    1.0
5   0x47012859fC5cB44d6106D54ff77580c85C380ecc        22.179    1.0
0   0x1E575FB7dD8b28CEcAD9065A7aFD1aC6c2fBA797        21.959    1.0
9   0x734C2a165e57496169aAAEA6E22aE763fF8d7654        19.778    1.0
8   0x730F19B7FA079EBfDc7360066ec593e4Bdd46Bf2        12.220    1.0
21  0xd87e862c34C5FEE08db543D851089a59589438d7         0.000    1.0
20  0xc364C71bAFAA85671C4d45E5Cf61bf19E0225AEb         0.000    1.0
19  0xaE7DB91DeC00E3Be062C7dC33288597DF023e0d6         0.000    1.0
18  0xC3C8b2915f62956066eD5C8719814e276A7B8C00         0.000    1.0
12  0x825FfDAB7d275dBAC844eFc36d5E8ce632d8E7A0         0.000    1.0
16  0xAe4fD4581D82C615105c798c73d1C33403d86ACB         0.000    1.0
15  0x91E0fA215FEc1F7D905f59F7FE03F9EF5090A8A8         0.000    2.0
14  0x8546601F9b4AcF1dc99C72cc48ED243d119cca95         0.000    3.0
13  0x844cae5EADD22CaE667F37388D788f79BDd97e62         0.000    1.0
10  0x7Cc1C96E6c20D6265531196d9ca2b3199fF8Ef9E         0.000    3.0
3   0x323FB5f356088ae979F12f27f94013e449BC62df         0.000    1.0
23  0xe8D423ca11ED809565BFA247d974d6EB42eB2DBb         0.000    1.0

In [31]:
df12 = df11[['supplier_ID','total_Ethash','count']].sort_values('total_Ethash', ascending = False)

In [32]:
df12.to_csv('ethash.csv', index = False)

In [33]:
df13 = pd.read_csv('ethash.csv')

In [34]:
df13

                                   supplier_ID  total_Ethash  count
0   0x26200241593722FA17DE5722Ed66d8830dc58C6D       219.539    1.0
1   0x672Ee945a55327328472B1a02437293945157f4C       186.411    1.0
2   0xd8B606a3D19C53E6Eea84ca5738D7D7d2c0eeb5f       159.643    1.0
3   0x70eC78FAF2CcD3fA3fe9567Fa5B8354Faa4e9457       129.860    1.0
4   0x37d7Ae51C3421474709331898B278D8bAB66eCac        85.636    1.0
5   0x7E74e1034bD9270482Fd286F03Cf7Fa26Bb99805        64.894    1.0
6   0xC1bf17F560FA5BF79aF72B4314d14706b90ad2cE        59.117    1.0
7   0x2f1B94E3813d66967a478031889F230D805130Ec        30.105    1.0
8   0x47012859fC5cB44d6106D54ff77580c85C380ecc        22.179    1.0
9   0x1E575FB7dD8b28CEcAD9065A7aFD1aC6c2fBA797        21.959    1.0
10  0x734C2a165e57496169aAAEA6E22aE763fF8d7654        19.778    1.0
11  0x730F19B7FA079EBfDc7360066ec593e4Bdd46Bf2        12.220    1.0
12  0xd87e862c34C5FEE08db543D851089a59589438d7         0.000    1.0
13  0xc364C71bAFAA85671C4d45E5Cf61bf19E0225AEb         0.000    1.0
14  0xaE7DB91DeC00E3Be062C7dC33288597DF023e0d6         0.000    1.0
15  0xC3C8b2915f62956066eD5C8719814e276A7B8C00         0.000    1.0
16  0x825FfDAB7d275dBAC844eFc36d5E8ce632d8E7A0         0.000    1.0
17  0xAe4fD4581D82C615105c798c73d1C33403d86ACB         0.000    1.0
18  0x91E0fA215FEc1F7D905f59F7FE03F9EF5090A8A8         0.000    2.0
19  0x8546601F9b4AcF1dc99C72cc48ED243d119cca95         0.000    3.0
20  0x844cae5EADD22CaE667F37388D788f79BDd97e62         0.000    1.0
21  0x7Cc1C96E6c20D6265531196d9ca2b3199fF8Ef9E         0.000    3.0
22  0x323FB5f356088ae979F12f27f94013e449BC62df         0.000    1.0
23  0xe8D423ca11ED809565BFA247d974d6EB42eB2DBb         0.000    1.0

In [35]:
df13['total_Ethash'].sum()

1011.3409999999999

In [36]:
print('Real-time total Ethash rate of the entire SONM platform is '+ str(df13['total_Ethash'].sum()) +' Mh/s')

Real-time total Ethash rate of the entire SONM platform is 1011.341 Mh/s

# Run the same statistics for consumers

In [37]:
df.groupby('consumer_ID').describe()['Ethash']

,count,mean,std,min,25%,50%,75%,max
consumer_ID,,,,,,,,
0x18CB84498d67635F14BA20A7A5DD9F8254bA5ecb,14.0,38.166286,66.131378,0.000,0.000,0.000,54.21525,219.539
0x417c92FbD944b125A578848DE44a4FD9132E0911,5.0,91.010800,76.831666,19.778,30.105,59.117,159.64300,186.411
0x49f6C95B97C209F814c5b3B13428E91686a1FEd9,3.0,0.000000,0.000000,0.000,0.000,0.000,0.00000,0.000
0x6f74D76F4c4b80A61598bdED7Fca2f660CA742Ce,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000
0xAAA932d77935EE3d8E0Ba1d464CFDA4E56566A01,1.0,21.959000,NaN,21.959,21.959,21.959,21.95900,21.959
0xB4214d064518eed303D966F9ca0Fc62Ac8dF20EE,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000
0xEe7Ff0a44C62209aa7dAa450F673415bC90bFC11,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000
0xF044524c6A30bC7559DEa1CB21fA11b1f5817833,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000
0xc620838fcaec0e5559aa111f77FC6016650c63E4,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000
0xe7517190DB97Ea55E985abdA33745AfC41a83592,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000

In [38]:
df10 = df.groupby('consumer_ID').describe()['Ethash']

In [39]:
df10.to_csv('consumer.csv')

In [40]:
df11 = pd.read_csv('consumer.csv')

In [41]:
df11['total_Ethash']= df11['mean']*df11['count']

In [42]:
df11

,consumer_ID,count,mean,std,min,25%,50%,75%,max,total_Ethash
0,0x18CB84498d67635F14BA20A7A5DD9F8254bA5ecb,14.0,38.166286,66.131378,0.000,0.000,0.000,54.21525,219.539,534.328
1,0x417c92FbD944b125A578848DE44a4FD9132E0911,5.0,91.010800,76.831666,19.778,30.105,59.117,159.64300,186.411,455.054
2,0x49f6C95B97C209F814c5b3B13428E91686a1FEd9,3.0,0.000000,0.000000,0.000,0.000,0.000,0.00000,0.000,0.000
3,0x6f74D76F4c4b80A61598bdED7Fca2f660CA742Ce,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000,0.000
4,0xAAA932d77935EE3d8E0Ba1d464CFDA4E56566A01,1.0,21.959000,NaN,21.959,21.959,21.959,21.95900,21.959,21.959
5,0xB4214d064518eed303D966F9ca0Fc62Ac8dF20EE,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000,0.000
6,0xEe7Ff0a44C62209aa7dAa450F673415bC90bFC11,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000,0.000
7,0xF044524c6A30bC7559DEa1CB21fA11b1f5817833,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000,0.000
8,0xc620838fcaec0e5559aa111f77FC6016650c63E4,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000,0.000
9,0xe7517190DB97Ea55E985abdA33745AfC41a83592,1.0,0.000000,NaN,0.000,0.000,0.000,0.00000,0.000,0.000

In [43]:
df11[['consumer_ID', 'total_Ethash', 'count']]

                                  consumer_ID  total_Ethash  count
0  0x18CB84498d67635F14BA20A7A5DD9F8254bA5ecb       534.328   14.0
1  0x417c92FbD944b125A578848DE44a4FD9132E0911       455.054    5.0
2  0x49f6C95B97C209F814c5b3B13428E91686a1FEd9         0.000    3.0
3  0x6f74D76F4c4b80A61598bdED7Fca2f660CA742Ce         0.000    1.0
4  0xAAA932d77935EE3d8E0Ba1d464CFDA4E56566A01        21.959    1.0
5  0xB4214d064518eed303D966F9ca0Fc62Ac8dF20EE         0.000    1.0
6  0xEe7Ff0a44C62209aa7dAa450F673415bC90bFC11         0.000    1.0
7  0xF044524c6A30bC7559DEa1CB21fA11b1f5817833         0.000    1.0
8  0xc620838fcaec0e5559aa111f77FC6016650c63E4         0.000    1.0
9  0xe7517190DB97Ea55E985abdA33745AfC41a83592         0.000    1.0

# Connor's deals

In [44]:
df[df.consumer_ID == '0x417c92FbD944b125A578848DE44a4FD9132E0911']

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,consumer_ID,supplier_ID,price,Ethash
4,"{""deal"":{""id"":""4692""","""benchmarks"":{""values"":[114",1525,4,512000000,67108864,1000000,1000000,2,8513388544,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W3sib3duZXJJRCI6IjB4NT...","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4ND...",None,0x417c92FbD944b125A578848DE44a4FD9132E0911,0xC1bf17F560FA5BF79aF72B4314d14706b90ad2cE,14615185000000,59.117
14,"{""deal"":{""id"":""4707""","""benchmarks"":{""values"":[103",1300,2,512000000,67108864,1000001,1000000,6,8511291392,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4ND...",None,0x417c92FbD944b125A578848DE44a4FD9132E0911,0xd8B606a3D19C53E6Eea84ca5738D7D7d2c0eeb5f,39510542500000,159.643
15,"{""deal"":{""id"":""4695""","""benchmarks"":{""values"":[104",1062,4,512000000,67108864,1000000,1000000,1,8512339968,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4ND...",None,0x417c92FbD944b125A578848DE44a4FD9132E0911,0x2f1B94E3813d66967a478031889F230D805130Ec,7431450000000,30.105
21,"{""deal"":{""id"":""4708""","""benchmarks"":{""values"":[105",1300,2,256000000,67108864,1000000,1000000,7,8513388544,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W10=""","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4ND...",None,0x417c92FbD944b125A578848DE44a4FD9132E0911,0x672Ee945a55327328472B1a02437293945157f4C,46212766000000,186.411
24,"{""deal"":{""id"":""4700""","""benchmarks"":{""values"":[108",1113,8,512000000,67108864,1000000,1000001,1,6368002048,...,"""netflags"":2","""askIdentityLevel"":1","""bidIdentityLevel"":1","""supplierCertificates"":""W3sib3duZXJJRCI6IjB4Nk...","""consumerCertificates"":""W3sib3duZXJJRCI6IjB4ND...",None,0x417c92FbD944b125A578848DE44a4FD9132E0911,0x734C2a165e57496169aAAEA6E22aE763fF8d7654,4830442500000,19.778

In [45]:
df12 = df[df.consumer_ID == '0x417c92FbD944b125A578848DE44a4FD9132E0911']

In [46]:
df12[['consumer_ID', 'supplier_ID', 'price', 'Ethash',0]]

,consumer_ID,supplier_ID,price,Ethash,0
4,0x417c92FbD944b125A578848DE44a4FD9132E0911,0xC1bf17F560FA5BF79aF72B4314d14706b90ad2cE,14615185000000,59.117,"{""deal"":{""id"":""4692"""
14,0x417c92FbD944b125A578848DE44a4FD9132E0911,0xd8B606a3D19C53E6Eea84ca5738D7D7d2c0eeb5f,39510542500000,159.643,"{""deal"":{""id"":""4707"""
15,0x417c92FbD944b125A578848DE44a4FD9132E0911,0x2f1B94E3813d66967a478031889F230D805130Ec,7431450000000,30.105,"{""deal"":{""id"":""4695"""
21,0x417c92FbD944b125A578848DE44a4FD9132E0911,0x672Ee945a55327328472B1a02437293945157f4C,46212766000000,186.411,"{""deal"":{""id"":""4708"""
24,0x417c92FbD944b125A578848DE44a4FD9132E0911,0x734C2a165e57496169aAAEA6E22aE763fF8d7654,4830442500000,19.778,"{""deal"":{""id"":""4700"""